/**
 * Core types for the quiz engine.
 *
 * These types are intentionally plain data (no functions embedded in the
 * serializable shapes) so that a `QuizDefinition` can be written by hand,
 * generated by an AI agent, or produced by a future no-code builder, and
 * then fed straight into `useQuizEngine` without modification.
 */

export type AnswerValue = string | number | boolean | string[];

/** All answers collected so far, keyed by step id. */
export type QuizAnswers = Record<string, AnswerValue | undefined>;

/**
 * A single branching rule evaluated against the current answers.
 * Rules for a step are evaluated in array order; the first match wins.
 * If no rule matches, the step's `next` fallback is used.
 */
export interface QuizBranchRule {
  /** Human-readable label, shown only in devtools/inspection, never at runtime. */
  label?: string;
  /**
   * Answer id to compare (usually the current step's id). Defaults to the
   * owning step's id if omitted.
   */
  answerId?: string;
  /** Match if the answer strictly equals this value. */
  equals?: AnswerValue;
  /** Match if the answer (array or string) includes this value. */
  includes?: string;
  /** Id of the step to go to when this rule matches. */
  goTo: string;
}

export interface QuizStepDefinition {
  /** Unique, stable id. Used as the key into `answers` and for branching. */
  id: string;
  /** Discriminates which component should render this step. Consumer-defined. */
  type: string;
  /** Arbitrary props forwarded to the step's component (question text, options, etc). */
  props?: Record<string, unknown>;
  /** Whether an answer is required to advance. Defaults to true. */
  required?: boolean;
  /** Branching rules, evaluated in order. */
  branch?: QuizBranchRule[];
  /**
   * Fallback next step id when no branch rule matches (or none are defined).
   * Omit on the last step of a linear path.
   */
  next?: string;
}

export interface QuizDefinition {
  id: string;
  title?: string;
  /** The id of the first step. */
  entry: string;
  steps: QuizStepDefinition[];
}

export interface QuizEngineState {
  currentStepId: string;
  /** Ids of steps visited, in order, for progress calculation and back-navigation. */
  history: string[];
  answers: QuizAnswers;
  status: "in-progress" | "complete";
}

export type QuizEngineAction =
  | { type: "ANSWER"; stepId: string; value: AnswerValue }
  | { type: "ADVANCE" }
  | { type: "BACK" }
  | { type: "GO_TO"; stepId: string }
  | { type: "RESET" };
